name: Auto Commit README

on:
  push:
    paths:
      - README.md
  schedule:
    - cron: '0 0 * * *'   # This will run daily at midnight UTC

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make changes to README.md
      run: |
        echo "Last updated on $(date)" >> README.md

    - name: Commit changes
      run: |
        git config --global user.name 'Prathamesh Chavan'
        git config --global user.email '145781960+Prathamesh-Chavan-98@users.noreply.github.com'
        git add README.md
        git commit -m "Update README.md automatically"
        git push
